---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Podcasts
- type: directory
  path: src/adv-in-angular
  label: Adventures in Angular
  create: all
  match: "*.md"
- type: directory
  path: src/adventures-in-blockchain
  label: Adventures in Blockchain
  create: all
  match: "*.md"
- type: directory
  path: src/adventures-in-devops
  label: Adventures in DevOps
  create: all
  match: "*.md"
- type: directory
  path: src/adventures-in-dotnet
  label: Adventures in DotNet
  create: all
  match: "*.md"
- type: directory
  path: src/clean-coders
  label: Clean Coders Podcast
  create: all
  match: "*.md"
- type: heading
  label: Admin
- type: directory
  path: src/_data/podcasts
  label: Podcasts
  create: all
  match: "*.json"
  new_doc_ext: json
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
