---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Podcasts
- type: directory
  path: src/adv-in-angular
  label: Adventures in Angular
  create: documents
  match: "*.md"
  templates:
  - adventures-in-angular
- type: directory
  path: src/adventures-in-blockchain
  label: Adventures in Blockchain
  create: documents
  match: "*.md"
  templates:
  - adventures-in-blockchain
- type: directory
  path: src/adventures-in-devops
  label: Adventures in DevOps
  create: all
  match: "*.md"
- type: directory
  path: src/adventures-in-dotnet
  label: Adventures in DotNet
  create: all
  match: "*.md"
- type: directory
  path: src/clean-coders
  label: Clean Coders
  create: all
  match: "*.md"
- type: directory
  path: src/dev-ed
  label: Dev Ed
  create: all
  match: "*.md"
- type: directory
  path: src/dev-rev
  label: The Dev Rev
  create: all
  match: "*.md"
- type: directory
  path: src/elixir-mix
  label: Elixir Mix
  create: all
  match: "**/*"
- type: directory
  path: src/freelancers
  label: Freelancers' Show
  create: all
  match: "*.md"
- type: directory
  path: src/iphreaks
  label: iPhreaks
  create: all
  match: "*.md"
- type: directory
  path: src/js-jabber
  label: JavaScript Jabber
  create: all
  match: "*.md"
- type: directory
  path: src/my-angular-story
  label: My Angular Story
  create: all
  match: "*.md"
- type: directory
  path: src/my-javascript-story
  label: My JavaScript Story
  create: all
  match: "*.md"
- type: directory
  path: src/my-ruby-story
  label: My Ruby Story
  create: all
  match: "*.md"
- type: directory
  path: src/react-native-radio
  label: React Native Radio
  create: all
  match: "*.md"
- type: directory
  path: src/react-round-up
  label: React Round Up
  create: all
  match: "*.md"
- type: directory
  path: src/ruby-rogues
  label: Ruby Rogues
  create: all
  match: "*.md"
- type: directory
  path: src/views-on-vue
  label: Views on Vue
  create: all
  match: "*.md"
- type: heading
  label: Podcasts on Hiatus
- type: directory
  path: src/rails-clips
  label: Rails Clips
  create: all
  match: "*.md"
- type: directory
  path: src/remote-conf-talks
  label: Remote Conference Talks
  create: all
  match: "*.md"
- type: directory
  path: src/sustain-our-software
  label: Sustain Our Software
  create: all
  match: "*.md"
- type: directory
  path: src/teachmetocode
  label: Teach Me to Code
  create: all
  match: "*.md"
- type: directory
  path: tmtc-screencasts
  label: Teach Me to Code Screencasts
  create: all
  match: "*.md"
- type: directory
  path: src/web-security-warriors
  label: Web Security Warriors
  create: all
  match: "*.md"
- type: heading
  label: Other Content
- type: directory
  path: src/blog
  label: Blog
  create: all
  match: "*.md"
- type: heading
  label: Admin
- type: directory
  path: src/_data/authors
  label: Authors
  create: all
  match: "*.json"
  new_doc_ext: json
- type: directory
  path: src/_data/podcasts
  label: Podcasts
  create: all
  match: "*.json"
  new_doc_ext: json
upload_dir: images/uploads
public_path: "/images/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: node --max_old_space_size=8192 node_modules/.bin/eleventy
    --serve
